name: Upload Node.js 14 and 16 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: laptop
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup Python 3.8
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Setup Python 3.9
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Setup Python 3.10
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Setup Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup pypy 3.8    
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.8' 
      - name: Setup Python 3.9
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9' 
      - name: Setup Python 3.10
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.10' 
      - name: Setup Python 3.7
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.7'
      - name: Setup Java 8
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Setup Java 11
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Setup Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
